apiVersion: v1
kind: Service
metadata:
  name: hubble-ui-lb
  namespace: kube-system
  annotations:
    "lbipam.cilium.io/ips": "192.168.1.220"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: hubble-ui
  type: LoadBalancer
  loadBalancerIP: "192.168.1.220"
