---
apiVersion: v1
kind: Service
metadata:
  name: network-tool
  annotations:
    "lbipam.cilium.io/ips": "192.168.1.221"
spec:
  selector:
    app: network-tool
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
