apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - git:
      repoURL: https://github.com/stianfro/rpi.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: 'app-{{path.basename}}'
    spec:
      project: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/stianfro/rpi.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc