apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    "lbipam.cilium.io/ips": "192.168.1.224"
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: "192.168.1.224"
