apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  annotations:
    "lbipam.cilium.io/ips": "192.168.1.223"
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
  loadBalancerIP: "192.168.1.223"
